// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSi-UkL9Z0jwRzvyyyrk3Bdb-ecRKsScA',
    appId: '1:225957636503:web:eefc4982510f8470a67cd2',
    messagingSenderId: '225957636503',
    projectId: 'blend-and-bloom',
    authDomain: 'blend-and-bloom.firebaseapp.com',
    databaseURL: 'https://blend-and-bloom-default-rtdb.firebaseio.com',
    storageBucket: 'blend-and-bloom.appspot.com',
    measurementId: 'G-85W206N29M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnzoX0WzMW08o2ACITVkzidJ0MEHvz8bA',
    appId: '1:225957636503:android:80ee5d5ab8bec767a67cd2',
    messagingSenderId: '225957636503',
    projectId: 'blend-and-bloom',
    databaseURL: 'https://blend-and-bloom-default-rtdb.firebaseio.com',
    storageBucket: 'blend-and-bloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDCsq2aKyDWUEzPbT5rsb3W0CGl9WB6A',
    appId: '1:225957636503:ios:688b17867ee860e3a67cd2',
    messagingSenderId: '225957636503',
    projectId: 'blend-and-bloom',
    databaseURL: 'https://blend-and-bloom-default-rtdb.firebaseio.com',
    storageBucket: 'blend-and-bloom.appspot.com',
    iosBundleId: 'com.example.project03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSi-UkL9Z0jwRzvyyyrk3Bdb-ecRKsScA',
    appId: '1:225957636503:web:223e4f6bd04cd208a67cd2',
    messagingSenderId: '225957636503',
    projectId: 'blend-and-bloom',
    authDomain: 'blend-and-bloom.firebaseapp.com',
    databaseURL: 'https://blend-and-bloom-default-rtdb.firebaseio.com',
    storageBucket: 'blend-and-bloom.appspot.com',
    measurementId: 'G-DZP50EWT5K',
  );
}
